### ISSUE TITLE
Compiles invalid TypeScript

### ISSUE THREAD

**Issue by mattdell** [anekpattanakij/next-typescript-example#1]
### Steps to reproduce

1) `yarn create next-app --example with-typescript with-typescript-app`
1) Open project
1) Navigate to index.tsx
1) Change line 5 from `const IndexPage: React.FunctionComponent` to `const IndexPage: React`

### Expected
Compilation error
```
Cannot use namespace 'React' as a type.ts(2709)
```

### Actual
```
Compiled successfully!
```

Given this setup I don't see any benefit to using TypeScript if it's going to just compile anyway.

**Comment by anekpattanakij** [comment]
I have updated package.json  to newer dependency version and instruction on readme file already.
It is able to compile and run properly now.

For TypeScript, it will help you for type checking when you are working with JS coding to make sure that you don't send nor receive wrong variable types between function.
